use_frameworks!

platform :ios, '10.0'

target 'GLToast-Swift_Example' do
  pod 'GLToast-Swift', :path => '../'

  target 'GLToast-Swift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
