use_frameworks!

platform :ios, '9.0'

target 'GLToast-Swift_Example' do
  pod 'GLToast-Swift', :path => '../'
#  pod 'GLToast-Swift', :git => 'https://github.com/ZhuGuiLei/GLToast-Swift.git'
  target 'GLToast-Swift_Tests' do
    inherit! :search_paths

#    pod 'GLToast-Swift', '1.3.0'
    
  end
end
